#ifndef MRVISUALLIB_GLOBAL_H
#define MRVISUALLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MRVISUALLIB_LIBRARY)
#  define MRVISUALLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MRVISUALLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MRVISUALLIB_GLOBAL_H
